### ISSUE TITLE
Error because Jar was not found

### ISSUE THREAD

**Issue by gablegar** [krasa/eclipse-code-formatter-intellij-plugin#66]
While trying to format I got this error:

java.lang.IllegalStateException: Plugin jar file not found: /Users/gablegar/Library/Application Support/IdeaIC2018.1/EclipseFormatter/lib/adapter44.jar
java.lang.RuntimeException: java.lang.IllegalStateException: Plugin jar file not found: /Users/MyUser/Library/Application Support/IdeaIC2018.1/EclipseFormatter/lib/adapter44.jar
	at krasa.formatter.eclipse.Classloaders.getGWTProcessor(Classloaders.java:153)
	at krasa.formatter.plugin.EclipseCodeFormatter.<init>(EclipseCodeFormatter.java:40)
	at krasa.formatter.plugin.EclipseCodeStyleManager.formatWithEclipse(EclipseCodeStyleManager.java:228)
	at krasa.formatter.plugin.EclipseCodeStyleManager.formatInternal(EclipseCodeStyleManager.java:138)
	at krasa.formatter.plugin.EclipseCodeStyleManager.reformatText(EclipseCodeStyleManager.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at krasa.formatter.plugin.ProxyCodeStyleManagerDelegator.invoke(ProxyCodeStyleManagerDelegator.java:41)
	at com.intellij.psi.codeStyle.CodeStyleManager$$EnhancerByCGLIB$$a6c18dd5.reformatText(<generated>)
	at com.intellij.codeInsight.actions.ReformatCodeProcessor.lambda$prepareTask$0(ReformatCodeProcessor.java:132)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1010)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.lambda$preprocessFile$0(AbstractLayoutCodeProcessor.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.lambda$preprocessFile$0(AbstractLayoutCodeProcessor.java:234)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.lambda$runProcessFile$2(AbstractLayoutCodeProcessor.java:343)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.lambda$null$5(AbstractLayoutCodeProcessor.java:425)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:137)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:95)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:71)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.lambda$null$6(AbstractLayoutCodeProcessor.java:423)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:786)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:727)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IllegalStateException: Plugin jar file not found: /Users/gablegar/Library/Application Support/IdeaIC2018.1/EclipseFormatter/lib/adapter44.jar
	at krasa.formatter.eclipse.Classloaders.classLoader(Classloaders.java:100)
	at krasa.formatter.eclipse.Classloaders.getEclipse44(Classloaders.java:29)
	at krasa.formatter.eclipse.Classloaders.getGWTProcessor(Classloaders.java:148)
	... 45 more

IntelliJ IDEA 2018.1.6 (Community Edition)
Build #IC-181.5540.7, built on July 11, 2018
JRE: 1.8.0_152-release-1136-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

**Comment by krasa** [comment]
Try to reinstall, and install the whole zip file, not extracted jar.

**Comment by gablegar** [comment]
This is not an issue.
